language: python
python:
  - 2.6
  - 2.7
sudo: false
env:
  - TOX_ENV=py26-django15
  - TOX_ENV=py27-django16
  - TOX_ENV=py27-django17
  - TOX_ENV=pep8

matrix:
  allow_failures:
    - env: TOX_ENV=pep8

install:
  - pip install tox coveralls

script:
  - tox -e $TOX_ENV

after_success:
  - coveralls
