language: python
python:
  - 2.7

sudo: false
env:
# commenting this out to save time because we know it would fail until python 2.6
# support won't be restored.
#  - TOX_ENV=py26-dj16-cms30
#  - TOX_ENV=py26-dj16-cms31
#  - TOX_ENV=py26-dj17-cms30
#  - TOX_ENV=py26-dj17-cms31
  - TOX_ENV=py27-dj16-cms30
  - TOX_ENV=py27-dj16-cms31
  - TOX_ENV=py27-dj17-cms30
  - TOX_ENV=py27-dj17-cms31
  - TOX_ENV=pep8

matrix:
  allow_failures:
    - env: TOX_ENV=pep8

before_install:
  - npm install -g npm

install:
  - pip install tox coveralls

before_script:
  - npm install -g gulp
  - npm install -g codeclimate-test-reporter
  - npm install

after_script:
  - codeclimate < tests/coverage/**/lcov.info

script:
  - tox -e $TOX_ENV
  - gulp tests

after_success:
  - coveralls

notifications:
  webhooks: http://addons.us-iad-rs.aldryn.io/en/travis-endpoint/
