language: python
python: 3.5
sudo: false

addons:
  apt:
    packages:
    - enchant

env:
  matrix:
    # Matrix-size reduction strategies:
    #   PY strategy: do not test 3.3 on Travis at all. (keep in tox.ini though)
    #   FE strategy: only test on Django/CMS3.3 combinations, but place tests on
    #                different Python ENVs if possible.
    - TOXENV=flake8

    - TOXENV=py35-dj19-cms34
    - TOXENV=py35-dj19-cms33-fe FE=1
    - TOXENV=py35-dj19-cms32
    - TOXENV=py34-dj19-cms34
    - TOXENV=py34-dj19-cms33
    - TOXENV=py34-dj19-cms32
    - TOXENV=py27-dj19-cms34
    - TOXENV=py27-dj19-cms33
    - TOXENV=py27-dj19-cms32

    - TOXENV=py35-dj18-cms34
    - TOXENV=py35-dj18-cms33
    - TOXENV=py35-dj18-cms32
    - TOXENV=py34-dj18-cms34
    - TOXENV=py34-dj18-cms33
    - TOXENV=py34-dj18-cms32
    - TOXENV=py27-dj18-cms34
    - TOXENV=py27-dj18-cms33-fe FE=1
    - TOXENV=py27-dj18-cms32

    - TOXENV=py34-dj17-cms32
    - TOXENV=py27-dj17-cms32

    - TOXENV=py27-dj16-cms32
    - TOXENV=py26-dj16-cms32

    # - TOXENV=doctest -- Re-enable once sphinxcontrib-spelling is https capable.

install:
  - pip install tox coveralls

before_script:
  - if [ "$FE" == 1 ]; then nvm install 6 && nvm use 6; fi
  - if [ "$FE" == 1 ]; then npm config set spin false; fi
  - if [ "$FE" == 1 ]; then npm install -g gulp@3.9.0; fi
  - if [ "$FE" == 1 ]; then npm install -g codeclimate-test-reporter; fi
  - if [ "$FE" == 1 ]; then npm install; fi

after_script:
  - codeclimate < tests/coverage/**/lcov.info

script:
  - tox -e $TOXENV

after_success:
  - coveralls

notifications:
  webhooks: http://addons.us-iad-rs.aldryn.io/en/travis-endpoint/
